name: release

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: extractions/setup-just@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.25.0'

      - run: just ship
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GH_USERNAME: ${{ github.actor }}
          GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

